<?php

use App\Http\Controllers\AccessTokenController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EventLogViewController;
use App\Http\Controllers\FavoriteProjectController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvitationController;
use App\Http\Controllers\OrganizationInvitationController;
use App\Http\Controllers\OrganizationMemberController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProjectDiagnosticsController;
use App\Http\Controllers\ProjectMemberController;
use App\Http\Controllers\RuleTemplateController;
use App\Http\Controllers\SegmentController;
use App\Http\Controllers\SegmentSuggestionController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('organizations/{organization}/dashboard', [DashboardController::class, 'show'])->name('organizations.dashboard');
    Route::get('organizations/{organization}/members', [OrganizationMemberController::class, 'index'])->name('organizations.members.index');
    Route::patch('organizations/{organization}/members/{member}', [OrganizationMemberController::class, 'update'])->name('organizations.members.update');
    Route::put('organizations/{organization}/members/{member}/projects', [OrganizationMemberController::class, 'syncProjects'])->name('organizations.members.projects.update');
    Route::delete('organizations/{organization}/members/{member}', [OrganizationMemberController::class, 'destroy'])->name('organizations.members.destroy');
    Route::post('organizations/{organization}/invitations', [OrganizationInvitationController::class, 'store'])->name('organizations.invitations.store');
    Route::delete('organizations/{organization}/invitations/{invitation}', [OrganizationInvitationController::class, 'destroy'])->name('organizations.invitations.destroy');
    Route::get('invitations', [InvitationController::class, 'index'])->name('invitations.index');
    Route::get('invitations/{invitation}', [InvitationController::class, 'show'])->middleware('signed')->name('invitations.show');
    Route::post('invitations/{invitation}/accept', [InvitationController::class, 'accept'])->name('invitations.accept');
    Route::post('invitations/{invitation}/decline', [InvitationController::class, 'decline'])->name('invitations.decline');
    Route::get('projects', [ProjectController::class, 'redirectIndex'])->name('projects.index');
    Route::get('organizations/{organization}/projects', [ProjectController::class, 'index'])->name('organizations.projects.index');
    Route::get('organizations/{organization}/projects/create', [ProjectController::class, 'create'])->name('organizations.projects.create');
    Route::post('organizations/{organization}/projects', [ProjectController::class, 'store'])->name('organizations.projects.store');
    Route::get('projects/{project}', [ProjectController::class, 'show'])->name('projects.show');
    Route::get('projects/{project}/edit', [ProjectController::class, 'edit'])->name('projects.edit');
    Route::put('projects/{project}', [ProjectController::class, 'update'])->name('projects.update');
    Route::get('projects/{project}/members', [ProjectMemberController::class, 'index'])->name('projects.members.index');
    Route::put('projects/{project}/members/{member}', [ProjectMemberController::class, 'update'])->name('projects.members.update');
    Route::delete('projects/{project}/members/{member}', [ProjectMemberController::class, 'destroy'])->name('projects.members.destroy');
    Route::get('projects/{project}/diagnostics', [ProjectDiagnosticsController::class, 'index'])->name('projects.diagnostics.index');
    Route::post('projects/{project}/diagnostics', [ProjectDiagnosticsController::class, 'evaluate'])->name('projects.diagnostics.evaluate');
    Route::post('projects/{project}/diagnostics/scenarios', [ProjectDiagnosticsController::class, 'store'])->name('projects.diagnostics.scenarios.store');
    Route::put('projects/{project}/diagnostics/scenarios/{diagnosticScenario}', [ProjectDiagnosticsController::class, 'update'])->name('projects.diagnostics.scenarios.update');
    Route::post('projects/{project}/diagnostics/scenarios/{diagnosticScenario}/run', [ProjectDiagnosticsController::class, 'run'])->name('projects.diagnostics.scenarios.run');
    Route::delete('projects/{project}/diagnostics/scenarios/{diagnosticScenario}', [ProjectDiagnosticsController::class, 'destroy'])->name('projects.diagnostics.scenarios.destroy');
    Route::post('projects/{project}/favorite', [FavoriteProjectController::class, 'store'])->name('projects.favorite.store');
    Route::delete('projects/{project}/favorite', [FavoriteProjectController::class, 'destroy'])->name('projects.favorite.destroy');
    Route::get('projects/{project}/segments', [SegmentController::class, 'index'])->name('projects.segments.index');
    Route::get('projects/{project}/segments/suggestions', [SegmentSuggestionController::class, 'index'])->name('projects.segments.suggestions');
    Route::get('projects/{project}/segments/create', [SegmentController::class, 'create'])->name('projects.segments.create');
    Route::post('projects/{project}/segments', [SegmentController::class, 'store'])->name('projects.segments.store');
    Route::post('projects/{project}/segments/copy', [SegmentController::class, 'copy'])->name('projects.segments.copy');
    Route::get('projects/{project}/segments/{segment}', [SegmentController::class, 'show'])->name('projects.segments.show');
    Route::get('projects/{project}/segments/{segment}/edit', [SegmentController::class, 'edit'])->name('projects.segments.edit');
    Route::put('projects/{project}/segments/{segment}', [SegmentController::class, 'update'])->name('projects.segments.update');
    Route::post('projects/{project}/segments/{segment}/duplicate', [SegmentController::class, 'duplicate'])->name('projects.segments.duplicate');
    Route::delete('projects/{project}/segments/{segment}', [SegmentController::class, 'destroy'])->name('projects.segments.destroy');
    Route::get('projects/{project}/rule-templates', [RuleTemplateController::class, 'index'])->name('projects.rule-templates.index');
    Route::post('projects/{project}/rule-templates', [RuleTemplateController::class, 'store'])->name('projects.rule-templates.store');
    Route::post('projects/{project}/rule-templates/copy', [RuleTemplateController::class, 'copy'])->name('projects.rule-templates.copy');
    Route::put('projects/{project}/rule-templates/{ruleTemplate}', [RuleTemplateController::class, 'update'])->name('projects.rule-templates.update');
    Route::delete('projects/{project}/rule-templates/{ruleTemplate}', [RuleTemplateController::class, 'destroy'])->name('projects.rule-templates.destroy');
    Route::get('projects/{project}/events', [EventLogViewController::class, 'index'])->name('projects.events.index');
    Route::get('projects/{project}/access-tokens', [AccessTokenController::class, 'index'])->name('projects.access-tokens.index');
    Route::post('projects/{project}/access-tokens', [AccessTokenController::class, 'store'])->name('projects.access-tokens.store');
    Route::patch('projects/{project}/access-tokens/{accessToken}', [AccessTokenController::class, 'update'])->name('projects.access-tokens.update');
    Route::post('projects/{project}/access-tokens/{accessToken}/rotate', [AccessTokenController::class, 'rotate'])->name('projects.access-tokens.rotate');
});

require __DIR__.'/settings.php';
